<!--

# Das Tidyverse - ggplot2

-->

## Visualisierung mit dem Paket `ggplot2`

### Die Grundidee

Der erste Teil von "_gg_plot2" steht für "Grammar of Graphics", also "Grammatik der Grafiken".

Diese Idee Grafiken nicht einfach nur zu Programmieren, sonden den gesamtn Prozess der Erstellung von Grafiken zu analysieren und für Nutzer:innen handhabbar zu machen geht u.a. auf das Buch "The Grammar of Graphics" <https://doi.org/10.1007/0-387-28695-0> von _Leland Wilkinson_ zurück.

Es versucht die Bereiche

Daten + Ästhetiken (aes) + Geome + Skalen + Facets + Themen

zu komibieren, so Grafiken einfach,klar zu beschreiben und den Computer dann daraus eine Graphik erstellen zu lassen.


## Beispiel: Streudiagram Körpermasse vs. Flossenlänge:

```{webr-r}
#| warning: false
#| autorun: true
penguins |>
    ggplot(aes(x = flipper_length_mm, 
               y = body_mass_g, 
               color = species, 
               shape = species)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "Penguin Größe, Palmer Station LTER",
       subtitle = "Flossenlänge und Körpermasse von Adelie, Chinstrap und Gentoo Penguinen",
       x = "Flossenlänge (in mm)", 
       y = "Körpermasse (in g)", 
       color = "Penguin Art", 
       shape = "Penguin Art") +
  theme_minimal()
```


## Beispiel: Flossenlänge vs. Schnabellänge

```{webr-r}
#| warning: false
#| autorun: true
ggplot(
    data = penguins, 
    aes(x = flipper_length_mm, 
        y = bill_length_mm, 
        color = species, 
        shape = species)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "Flossen- und Schnabellänge",
       subtitle = "Dimensionen von Adelie, Chinstrap and Gentoo Penguinen",
       x = "Flossenlänge (in mm)", 
       y = "Schnabellänge (in mm)", 
       color = "Penguin Art", 
       shape = "Penguin Art") +
  theme_minimal()
```


## Beispiel: Histogramm der Körpermasse:

```{webr-r}
#| warning: false
#| autorun: true
ggplot(data = penguins, aes(x = body_mass_g)) +
  geom_histogram(bins = 30, fill = "steelblue", alpha = 0.7) +
  labs(title = "Verteilung der Körpermasse von Palmer Penguinen", x = "Körpergewicht (in g)", y = "Anzahl") +
  theme_minimal()
```


## Beispiel: Boxplot der Körpermasse nach Art

```{webr-r}
#| warning: false
#| autorun: true
ggplot(data = penguins, aes(x = species, y = body_mass_g, fill = species)) +
  geom_boxplot() +
  labs(title = "Körpermasse der Penguin Arten", x = "Arten", y = "Körpermasse (in g)") +
  theme_minimal()
```


## Datum mit dem Paket `lubridate`

Die R-Bibliothek `lubridate` wird verwendet, um Datums- und Zeitangaben einfach zu verarbeiten und zu manipulieren. 

Wir nutzen hier die Befehle `make_datetime()` um aus den Datumsangaben eine `datetime()` zu bilden.

Und den Befehl `wday()`, der und aus einem Datum den Wochentag berechnet.


## Vorbereitung

Wir schauen uns jetzt nur die Flüge im Januar an und fügen den Wochentag (*wday*) und die Abflugszeit (*dep_datetime*) hinzu:

```{webr-r}
#| warning: false
#| autorun: true
flights |> 
    filter(month == 1) |>
    mutate(
        dep_datetime = make_datetime(year, month, day, hour, minute),
        wday = wday(dep_datetime, label = TRUE, locale="de_DE")) -> jan_flights
```


## Säulendiagramm: Flüge nach Wochentag im Januar

```{webr-r}
#| warning: false
#| autorun: true
ggplot(jan_flights, aes(x = wday)) +
  geom_bar(fill = "coral") +
  labs(title = "Flüge nach Wochentag im Januar", x = "Wochentag", y = "Anzahl Flüge")
```


## Streudiagramm Ankunfts- vs. Abflugverzögerungen im Januar

```{webr-r}
#| warning: false
#| autorun: true
ggplot(jan_flights, 
       aes(x = dep_delay, y = arr_delay, color = carrier)) +
  geom_point(alpha = 0.5) +
  labs(title = "Ankunfts- vs. Abflugverzögerungen im Januar", 
       x = "Abflugverspätung (in Minuten)", 
       y = "Ankunftsverspätung (in Minuten)")
```


## Aufgaben {.Übung}

1. Erstellen Sie eine Tabelle für den August mit dem Namen *aug_flights*

2. Fügen Sie von den Fluggesellschaftkürzen auch die ensprechenden Namen der Fluggesellschaften in diese Tabelle ein.

3. Eben Sie die Flüge nach Wochentag im August als Säulendiagramm aus.

