<!--

# Ein kurze Einführung in unser Arbeitsumgebung

-->

## RStudio, posit.cloud oder Positron? 

- [R](https://www.r-project.org) \
    Die Skript-Sprache mit der wir hier arbeiten werden. 
    Dazu ein eigener Abschnitt später.


- [RStudio (Desktop)](https://posit.co/download/rstudio-desktop/) \
    Eine *Integrierte Entwicklungsumgeben* (IDE) für R, die uns den Umgang 
    sehr stark erleichtert.

- [posit.cloud](https://posit.cloud) \
    Ursprunglich *RStudio cloud*, jetzt aber *posit.cloud* ist eine 
    Cloud-Version von *RStudio Desktop*. 
    Wir nutzen hier diesen Zugang, da er einen schnellern Zungang ermöglicht.

- Die Zukunft: [positron](https://positron.posit.co) \
    Der Nachfolger von _RStudio Desktop_ ist  in der Pipeline. 
    Er heißt _Positron_



## posit.cloud

Wir nutzen **posit.cloud** als Cloud-Version von *R* bzw. *RStudio*.

Für diese Einführung reicht das vollkommen aus. 
Sie sollten aber, wenn Sie öfters mit R arbeiten, darüber nachdenken _R_ und _R Studio_ oder _Positron_ lokal auf ihren Rechner zu installieren. 
Anleitungen finden Sie dazu reichlich im Internet.
Auch auf den auf den Seiten der [FOM](https://www.fom.de) unter <https://fomshinyapps.shinyapps.io/Installation-R-RStudio-mosaic/> bzw. <https://raw.githubusercontent.com/luebby/Datenanalyse-mit-R/master/Installation/Install.pdf>


## Wo ist was?

Live: Die ersten Schritte in der *posit.cloud*!



